### ISSUE TITLE
Check this is out

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Stack_Hack_1.0_client#52]
## Guys I made the login and signup page like this 

# Connect on the design. 

**Close the issue when resolved**
![image](https://user-images.githubusercontent.com/41781438/82873516-3eebd900-9f52-11ea-8990-b135ae78e69a.png)

**Comment by imabp** [comment]
@Souvikns  ohh thats great. This would be the homepage of our app right!

**Comment by Souvikns** [comment]
Yes if no data in the session. 
Should I change the picture with something that fits with our web-app? 
I added that picture, I had a login page in my mind.

**Comment by imabp** [comment]
umm yaa.. related to todos ...it would be great

**Comment by Souvikns** [comment]
On it bro. 
*closing this issue*
